***Descriptive Analysis***

***About Dataset***

***This descriptive analysis aims to understand smartphone usage behavior across different user demographics. The dataset includes metrics such as screen time, total app usage, category-wise app usage (social media, productivity, gaming), and number of apps used, along with demographic attributes like age, gender, and location.***

* ***User_ID***: *A unique numeric identifier assigned to each participant in the mobile usage dataset.*

* ***Age***: *The age of the user in years, representing the demographic distribution across young, adult, and older populations.*

* ***Gender***: *The gender identity of the user (Male/Female), used for studying gender-wise variations in mobile usage behavior.*

* ***Total_App_Usage_Hours***: *The total number of hours the user spends using different apps daily, summing all app categories.*

* ***Daily_Screen_Time_Hours***: *The total screen-on time per day, including active usage, browsing, and passive device engagement.*

* ***Number_of_Apps_Used***: *The total count of mobile applications actively used by the user within the observed period.*

* ***Social_Media_Usage_Hours***: *Daily time (in hours) spent on social media platforms such as Instagram, Facebook, Snapchat, and similar apps.*

* ***Productivity_App_Usage_Hours***: *Daily time (in hours) spent on productivity-oriented apps such as calendars, note-taking apps, emails, and task managers.*

* ***Gaming_App_Usage_Hours***: *Daily time (in hours) spent on gaming apps, ranging from casual mobile games to high-engagement gaming applications.*

* ***Location***: *The city or region where the user resides, used to analyze geographic differences in smartphone usage behavior.*

In [5]:
import numpy as np
import pandas as pd
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [6]:
df = pd.read_csv("/Users/meenakshsinghania04/Desktop/DM--Smartphone-Usage-and-app-trends/data/processed/mobile_usage_behavioral_analysis_cleaned.csv")

In [7]:
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())

Shape: (1000, 10)
Columns: ['User_ID', 'Age', 'Gender', 'Total_App_Usage_Hours', 'Daily_Screen_Time_Hours', 'Number_of_Apps_Used', 'Social_Media_Usage_Hours', 'Productivity_App_Usage_Hours', 'Gaming_App_Usage_Hours', 'Location']

In [8]:
df.head()

,User_ID,Age,Gender,Total_App_Usage_Hours,Daily_Screen_Time_Hours,Number_of_Apps_Used,Social_Media_Usage_Hours,Productivity_App_Usage_Hours,Gaming_App_Usage_Hours,Location
0,1.0,56.0,Male,2.61,7.15,24.0,4.43,0.55,2.40,Los Angeles
1,2.0,46.0,Male,2.13,13.79,18.0,4.67,4.42,2.43,Chicago
2,3.0,32.0,Female,7.28,4.50,11.0,4.58,1.71,2.83,Houston
3,4.0,25.0,Female,1.20,6.29,21.0,3.18,3.42,4.58,Phoenix
4,5.0,38.0,Male,6.31,12.59,14.0,3.15,0.13,4.00,New York

In [9]:
df.describe()

,User_ID,Age,Total_App_Usage_Hours,Daily_Screen_Time_Hours,Number_of_Apps_Used,Social_Media_Usage_Hours,Productivity_App_Usage_Hours,Gaming_App_Usage_Hours
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000
mean,500.500000,38.745000,6.405670,7.696310,16.64700,2.456330,2.495270,2.475410
std,288.819436,12.186734,3.134855,3.714187,7.61961,1.439525,1.443392,1.450362
min,1.000000,18.000000,1.000000,1.010000,3.00000,0.000000,0.000000,0.010000
25%,250.750000,28.000000,3.590000,4.530000,10.00000,1.200000,1.282500,1.220000
50%,500.500000,40.000000,6.455000,7.880000,17.00000,2.445000,2.435000,2.455000
75%,750.250000,50.000000,9.122500,10.910000,23.00000,3.672500,3.710000,3.782500
max,1000.000000,59.000000,11.970000,14.000000,29.00000,4.990000,5.000000,5.000000

In [10]:
df.columns = [
    'User_ID','Age','Gender','Total_App_Usage_Hours','Daily_Screen_Time_Hours','Number_of_Apps_Used',
    'Social_Media_Usage_Hours','Productivity_App_Usage_Hours','Gaming_App_Usage_Hours', 'Location',
]

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   User_ID                       1000 non-null   float64
 1   Age                           1000 non-null   float64
 2   Gender                        1000 non-null   object
 3   Total_App_Usage_Hours         1000 non-null   float64
 4   Daily_Screen_Time_Hours       1000 non-null   float64
 5   Number_of_Apps_Used           1000 non-null   float64
 6   Social_Media_Usage_Hours      1000 non-null   float64
 7   Productivity_App_Usage_Hours  1000 non-null   float64
 8   Gaming_App_Usage_Hours        1000 non-null   float64
 9   Location                      1000 non-null   object
dtypes: float64(8), object(2)
memory usage: 78.3+ KB

In [12]:
def compute_stats(series):
    data = series.dropna().values

    mean = np.mean(data)
    median = np.median(data)
    mode = stats.mode(data, keepdims=True)[0][0]
    std = np.std(data)

    p25 = np.percentile(data, 25)
    p75 = np.percentile(data, 75)
    iqr = p75 - p25
    lower = p25 - 1.5 * iqr
    upper = p75 + 1.5 * iqr

    outliers = data[(data < lower) | (data > upper)]

    z = stats.zscore(data)
    anomalies = data[np.abs(z) > 3]

    return {
        "mean": mean,
        "median": median,
        "mode": mode,
        "std_dev": std,
        "iqr": iqr,
        "outliers_count": len(outliers),
        "anomalies_count": len(anomalies)
    }

In [13]:
num_cols = df.select_dtypes(include=['int64','float64']).columns.tolist()

In [14]:
numerical_col_results = {}

for col in num_cols:
    numerical_col_results[col] = compute_stats(df[col])

numerical_col_results

{'User_ID': {'mean': np.float64(500.5),
  'median': np.float64(500.5),
  'mode': np.float64(1.0),
  'std_dev': np.float64(288.6749902572095),
  'iqr': np.float64(499.5),
  'outliers_count': 0,
  'anomalies_count': 0},
 'Age': {'mean': np.float64(38.745),
  'median': np.float64(40.0),
  'mode': np.float64(50.0),
  'std_dev': np.float64(12.180639351035724),
  'iqr': np.float64(22.0),
  'outliers_count': 0,
  'anomalies_count': 0},
 'Total_App_Usage_Hours': {'mean': np.float64(6.40567),
  'median': np.float64(6.455),
  'mode': np.float64(7.14),
  'std_dev': np.float64(3.1332874670384143),
  'iqr': np.float64(5.532499999999999),
  'outliers_count': 0,
  'anomalies_count': 0},
 'Daily_Screen_Time_Hours': {'mean': np.float64(7.69631),
  'median': np.float64(7.88),
  'mode': np.float64(8.14),
  'std_dev': np.float64(3.7123294955997643),
  'iqr': np.float64(6.38),
  'outliers_count': 0,
  'anomalies_count': 0},
 'Number_of_Apps_Used': {'mean': np.float64(16.647),
  'median': np.float64(17.0),
  'mode': np.float64(10.0),
  'std_dev': np.float64(7.615798776228268),
  'iqr': np.float64(13.0),
  'outliers_count': 0,
  'anomalies_count': 0},
 'Social_Media_Usage_Hours': {'mean': np.float64(2.45633),
  'median': np.float64(2.4450000000000003),
  'mode': np.float64(3.36),
  'std_dev': np.float64(1.4388052095749446),
  'iqr': np.float64(2.4725),
  'outliers_count': 0,
  'anomalies_count': 0},
 'Productivity_App_Usage_Hours': {'mean': np.float64(2.4952699999999997),
  'median': np.float64(2.435),
  'mode': np.float64(1.29),
  'std_dev': np.float64(1.4426706232193127),
  'iqr': np.float64(2.4275),
  'outliers_count': 0,
  'anomalies_count': 0},
 'Gaming_App_Usage_Hours': {'mean': np.float64(2.4754099999999997),
  'median': np.float64(2.455),
  'mode': np.float64(0.26),
  'std_dev': np.float64(1.449636655131209),
  'iqr': np.float64(2.5625),
  'outliers_count': 0,
  'anomalies_count': 0}}

In [15]:
categorical_cols = df.select_dtypes(include='object').columns.tolist()

In [16]:
encoder = LabelEncoder()
df_cat_encoded = df[categorical_cols].apply(encoder.fit_transform)

In [17]:
scaler = StandardScaler()
df_cat_scaled = pd.DataFrame(scaler.fit_transform(df_cat_encoded), columns=categorical_cols)

In [18]:
categorical_results = {}

for col in df_cat_scaled.columns:
    categorical_results[col] = compute_stats(df_cat_scaled[col])

categorical_results

{'Gender': {'mean': np.float64(-6.927791673660977e-17),
  'median': np.float64(0.966558832554526),
  'mode': np.float64(0.966558832554526),
  'std_dev': np.float64(1.0),
  'iqr': np.float64(2.0011570032184807),
  'outliers_count': 0,
  'anomalies_count': 0},
 'Location': {'mean': np.float64(-5.329070518200751e-17),
  'median': np.float64(-0.053980540307868294),
  'mode': np.float64(0.6562897269009244),
  'std_dev': np.float64(0.9999999999999999),
  'iqr': np.float64(1.4205405344175852),
  'outliers_count': 0,
  'anomalies_count': 0}}